<a href="https://colab.research.google.com/github/rajarameshchindu/pytorch/blob/main/002_pytorch_what_are_tensors_in_pytorch_1_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
x = torch.tensor([4., 2., 6.])
y = torch.tensor([3., 19., 12.])

# Addition
torch.add(x, y)

NameError: ignored

In [2]:
import torch

In [3]:
x = torch.tensor([4., 2., 6.])
y = torch.tensor([3., 19., 12.])

# Addition
torch.add(x, y)

tensor([ 7., 21., 18.])

In [4]:
# Subtraction
torch.sub(x, y)

tensor([  1., -17.,  -6.])

In [5]:
# Multiplication
torch.mul(x, y)

tensor([12., 38., 72.])